"""NEXUS Task models — task lifecycle, steps, and tool executions.

Per Domain Architecture (Backend Architecture §10 & §13):
Tasks flow through a strict state machine and contain ordered steps
executed by specialized agents.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from sqlalchemy import ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from nexus.models.base import Base, PrefixedIdMixin, TimestampMixin, _generate_prefixed_id

if TYPE_CHECKING:
    from nexus.models.approval import Approval
    from nexus.models.project import Project


class Task(PrefixedIdMixin, TimestampMixin, Base):
    """An engineering task submitted by the user.

    Tasks follow the state machine defined in Backend Architecture §13:
    CREATED → QUEUED → ANALYZING → PLANNING → [WAITING_APPROVAL] →
    EXECUTING → TESTING → [DEBUGGING] → SECURITY_CHECK → REVIEWING → COMPLETED
    """

    __tablename__ = "tasks"

    # Parent project
    project_id: Mapped[str] = mapped_column(
        String(50), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )

    # User's natural language goal / instruction
    goal: Mapped[str] = mapped_column(Text, nullable=False)

    # Current state in the task state machine
    status: Mapped[str] = mapped_column(String(30), default="created", nullable=False)

    # Git branch created for this task (e.g., nexus/tsk_abc123-fix-auth)
    branch_name: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Selected LLM model for this task
    model: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # Number of debug retry cycles consumed (max 3)
    debug_retries: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # Summary generated by the Reviewer agent after completion
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Error message if task failed
    error: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Relationships
    project: Mapped[Project] = relationship("Project", back_populates="tasks")

    steps: Mapped[list[TaskStep]] = relationship(
        "TaskStep",
        back_populates="task",
        cascade="all, delete-orphan",
        order_by="TaskStep.step_order",
        lazy="selectin",
    )

    approvals: Mapped[list[Approval]] = relationship(
        "Approval",
        back_populates="task",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    def __init__(self, **kwargs: object) -> None:
        if "id" not in kwargs:
            kwargs["id"] = _generate_prefixed_id("tsk")
        super().__init__(**kwargs)

    def __repr__(self) -> str:
        return f"<Task id={self.id!r} status={self.status!r}>"


# Valid state transitions (from -> set of allowed destinations)
VALID_TASK_TRANSITIONS: dict[str, set[str]] = {
    "created": {"queued", "cancelled"},
    "queued": {"analyzing", "cancelled"},
    "analyzing": {"planning", "failed", "cancelled"},
    "planning": {"waiting_approval", "executing", "failed", "cancelled"},
    "waiting_approval": {"executing", "failed", "cancelled"},
    "executing": {"testing", "failed", "cancelled"},
    "testing": {"debugging", "security_check", "failed", "cancelled"},
    "debugging": {"testing", "failed", "cancelled"},
    "security_check": {"reviewing", "failed", "cancelled"},
    "reviewing": {"completed", "failed", "cancelled"},
    # Terminal states
    "completed": set(),
    "failed": set(),
    "cancelled": set(),
}


class TaskStep(PrefixedIdMixin, TimestampMixin, Base):
    """A single step within a task, executed by a specific agent.

    Each agent in the pipeline (Planner, Developer, Tester, etc.)
    produces one or more TaskStep records.
    """

    __tablename__ = "task_steps"

    # Parent task
    task_id: Mapped[str] = mapped_column(
        String(50), ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False
    )

    # Which agent executed this step
    agent_type: Mapped[str] = mapped_column(String(30), nullable=False)

    # Step ordering within the task
    step_order: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Step status: pending, running, completed, failed, skipped
    status: Mapped[str] = mapped_column(String(20), default="pending", nullable=False)

    # Agent's input context (summarized)
    input_summary: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Agent's output / result
    output: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Error details if step failed
    error: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Token usage
    tokens_used: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # Relationships
    task: Mapped[Task] = relationship("Task", back_populates="steps")

    tool_executions: Mapped[list[ToolExecution]] = relationship(
        "ToolExecution",
        back_populates="step",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    def __init__(self, **kwargs: object) -> None:
        if "id" not in kwargs:
            kwargs["id"] = _generate_prefixed_id("stp")
        super().__init__(**kwargs)

    def __repr__(self) -> str:
        return f"<TaskStep id={self.id!r} agent={self.agent_type!r} status={self.status!r}>"


class ToolExecution(PrefixedIdMixin, TimestampMixin, Base):
    """A record of a single tool invocation during a task step.

    Every tool call (read_file, write_file, git_diff, etc.)
    is logged as an immutable ToolExecution.
    """

    __tablename__ = "tool_executions"

    # Parent step
    step_id: Mapped[str] = mapped_column(
        String(50), ForeignKey("task_steps.id", ondelete="CASCADE"), nullable=False
    )

    # Tool identifier (e.g., "read_file", "execute_command")
    tool_name: Mapped[str] = mapped_column(String(100), nullable=False)

    # Risk level: read_only, low, medium, high, critical
    risk_level: Mapped[str] = mapped_column(String(20), default="low", nullable=False)

    # Tool input parameters (JSON string)
    input_params: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Tool output (JSON string, may be truncated)
    output: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Execution status: pending, running, completed, failed, rejected
    status: Mapped[str] = mapped_column(String(20), default="pending", nullable=False)

    # Execution duration in milliseconds
    duration_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # If this tool required approval, link to the approval record
    approval_id: Mapped[str | None] = mapped_column(
        String(50), ForeignKey("approvals.id", ondelete="SET NULL"), nullable=True
    )

    # Error message if execution failed
    error: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Relationships
    step: Mapped[TaskStep] = relationship("TaskStep", back_populates="tool_executions")

    def __init__(self, **kwargs: object) -> None:
        if "id" not in kwargs:
            kwargs["id"] = _generate_prefixed_id("tex")
        super().__init__(**kwargs)

    def __repr__(self) -> str:
        return f"<ToolExecution id={self.id!r} tool={self.tool_name!r}>"
